### ISSUE TITLE
What's the best way of using a dataset without metadata?

### ISSUE THREAD

**Issue by dimeldo** [snakeztc/NeuralDialog-LAED#2]
Looking at `DailyDialogSkipLoader`, It's apparent in this line that metadata like dialog acts and emotion are being appended to the dialogue.

```
dialog.append(Pack(utt=utt, speaker=t_id%2,
                                   meta={'emotion': raw_emotion[t_id], 'act': raw_act[t_id]}))

```
 I'm using a dataset without such metadata, how should I change the code?
Should I put None/0 or remove the meta parameter completely?

**Comment by snakeztc** [comment]
You can simply modify the data loader to set meta to be None. The meta is not used anywhere for training, it's only used for evaluation. @dimeldo
